version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravelnet

  php1:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php1
    volumes:
      - .:/var/www/html
    networks:
      - laravelnet
    depends_on:
      - mysql
    environment:
       SERVER_NAME: "Serveur 1"

  php2:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php2
    volumes:
      - .:/var/www/html
    networks:
      - laravelnet
    depends_on:
      - mysql
    environment:
      SERVER_NAME: "Serveur 2"

  nginx1:
    image: nginx:latest
    container_name: nginx1
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx1.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php1
    networks:
      - laravelnet

  nginx2:
    image: nginx:latest
    container_name: nginx2
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx2.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php2
    networks:
      - laravelnet

volumes:
  db_data:

networks:
  laravelnet:
